name: MyPy

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}

defaults:
  run:
    shell: bash

jobs:

  mypy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout ðŸ›Žï¸
      uses: actions/checkout@v3
    - name: Set up Python ðŸ 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Get pip cache dir
      id: pip-cache
      run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-mypy-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-mypy

    - name: Install dependencies
      run: |
        pip install -e '.[test]' --extra-index-url https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install mypy==1.5.0  # don't use --upgrade to respect the version installed via setup.py
        pip list

    - name: Check typing
      # mypy uses the config file found in the following order:
      # 1. mypy.ini
      # 2. pyproject.toml
      # 3. setup.cfg
      # 4. $XDG_CONFIG_HOME/mypy/config
      # 5. ~/.config/mypy/config
      # 6. ~/.mypy.ini
      # https://mypy.readthedocs.io/en/stable/config_file.html
      run: mypy
